map_type: costmap

obstacle_range: 1.0
raytrace_range: 3.0
cost_scaling_factor: 5

transform_tolerance: 3

inflation_radius: 0.5

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}